on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: cargo test
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/release
  publish:
    runs-on: ubuntu-24.04
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Publish (PR)
        if: github.event_name == 'pull_request'
        run: cargo publish --dry-run
      - name: Publish
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: cargo publish --token "${{ secrets.CARGO_TOKEN }}"